import numpy as np
from sklearn.svm import SVC


def train_svm(folder):
    """
    Train a linear Support Vector Machine on the preprocessed dataset produced by
    `gen`, evaluate its accuracy on the held-out test set, and persist the result.
    Runs concurrently with train_rf.
    """
    # Download the preprocessed arrays generated by `gen`
    for fname in ["X_train.npy", "X_test.npy", "y_train.npy", "y_test.npy"]:
        faasr_get_file(remote_folder=folder, remote_file=fname, local_file=fname)

    X_train = np.load("X_train.npy")
    X_test = np.load("X_test.npy")
    y_train = np.load("y_train.npy")
    y_test = np.load("y_test.npy")

    # Train the SVM classifier
    clf = SVC(kernel="linear", C=0.025)
    clf.fit(X_train, y_train)

    # Evaluate accuracy
    accuracy = clf.score(X_test, y_test)

    # Persist the accuracy result to S3
    with open("svm_accuracy.txt", "w") as fh:
        fh.write(str(accuracy))
    faasr_put_file(
        local_file="svm_accuracy.txt",
        remote_folder=folder,
        remote_file="svm_accuracy.txt",
    )

    faasr_log(f"train_svm: SVC(kernel='linear', C=0.025) test accuracy = {accuracy}")
