import numpy as np
from sklearn.ensemble import RandomForestClassifier


def train_rf(folder):
    """
    Train a Random Forest classifier on the preprocessed dataset produced by
    `gen`, evaluate its accuracy on the held-out test set, and persist the result.
    Runs concurrently with train_svm.
    """
    # Download the preprocessed arrays generated by `gen`
    for fname in ["X_train.npy", "X_test.npy", "y_train.npy", "y_test.npy"]:
        faasr_get_file(remote_folder=folder, remote_file=fname, local_file=fname)

    X_train = np.load("X_train.npy")
    X_test = np.load("X_test.npy")
    y_train = np.load("y_train.npy")
    y_test = np.load("y_test.npy")

    # Train the Random Forest classifier (no explicit seeding)
    clf = RandomForestClassifier(max_depth=5, n_estimators=10)
    clf.fit(X_train, y_train)

    # Evaluate accuracy
    accuracy = clf.score(X_test, y_test)

    # Persist the accuracy result to S3
    with open("rf_accuracy.txt", "w") as fh:
        fh.write(str(accuracy))
    faasr_put_file(
        local_file="rf_accuracy.txt",
        remote_folder=folder,
        remote_file="rf_accuracy.txt",
    )

    faasr_log(
        f"train_rf: RandomForestClassifier(max_depth=5, n_estimators=10) "
        f"test accuracy = {accuracy}"
    )
